from bson import Binary
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["Travistor"]
collection = db["package_details"]

data_to_add=[{"_id":1,"title" : "Rajasthan","route":"Day 1:Jaipur (2 Nights)-->Day 2:Jaipur-->Day 3:Jaipur–Pushkar (1 Night)-->Day 4:Pushkar–Chittorgarh–Udaipur (2 Nights)-->Day 5:Udaipur-->Day 6:Udaipur–Departure","price":"34,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/wom2.jpg", "rb").read())},
             {"_id":2,"title" : "Shimla Manali","route":"Day 1:Delhi–Chandigarh (1 Night)-->Day 2:Chandigarh–Shimla (1 Night)-->Day 3:Shimla – Manali (3 Nights)-->Day 4:Manali-->Day 5:Manali – Solang Valley – Manali-->Day 6:Manali – Chandigarh (1 Night)-->Day 7:Chandigarh – Delhi – Departure","price":"₹39,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/wom3.jpg", "rb").read())},
             {"_id":3,"title" : "Kerala","route":"Day 1 / 05 Mar, 24Cochin – Alleppey (1 Night)-->Day 2:Alleppy – Periyar (1 Night)-->Day 3:Periyar – Munnar (2 Nights)-->Day 4:Munnar-->Day 5:Munnar – Cochin (1 Night)-->Day 6:Cochin – Departure","price":"43,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/wom4.jpg", "rb").read())},
             {"_id":4,"title" : "Patan Modhera","route":"Day 1:Ahmedabad – Kevadia (2 Nights)-->Day 2:Kevadia-->Day 3:Kevadia–Ahmedabad (2 Nights)-->Day 4:Ahmedabad–Patan–Modhera–Ahmedabad-->Day 5:Ahmedabad–Departure to Hometown","price":"₹34,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/wom1.jpg", "rb").read())},
             {"_id":5,"title" : "Coorg Mysore Bengaluru","route":"Day 1:Bangalore–Mysore (2 Nights)-->Day 2:Mysore-->Day 3:Mysore–Coorg (2 Nights)-->Day 4:Coorg-->Day 5:Coorg–Bangalore (1 Night)-->Day 6:Bangalore–Departure","price":"₹16,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/wom5.jpg", "rb").read())},
             {"_id":6,"title" : "Nainital Mussoorie Haridwar","route":"Day 1:Delhi–Nainital/Bhimtal (2 Nights)-->Day 2:Nainital/Bhimtal-->Day 3:Nainital–Mussoorie (2 Nights)-->Day 4:Mussoorie-->Day 5:Mussoorie–Rishikesh–Haridwar (1 Night)-->Day 6:Haridwar–Delhi–Departure","price":"₹45,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/wom6.jpg", "rb").read())},
             {"_id":7,"title" : "Gujarat","route":"Day1:Ahmedabad–Gir (1 Night)-->Day 2:Sasan Gir–Somnath (1 Night)-->Day 3:Somnath–Dwarka (2 Nights)-->Day 4:Dwarka-->Day 5:Dwarka–Ahmedabad (2 Nights)-->Day 6:Ahmedabad–Patan–Modhera–Ahmedabad-->Day 7:Ahmedabad–Departure","price":"₹20,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/senior1.jpg", "rb").read())},
             {"_id":8,"title" : "Indore Ujjain Mandu","route":"Day 1:Indore (4 Nights)-->Day 2:Indore–Omkareshwar–Maheshwar–Indore-->Day 3:Indore–Ujjain–Indore-->Day 4:Indore–Mhow–Mandu–Indore-->Day 5:Indore–Departure","price":"₹38,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/senior2.jpg", "rb").read())},
             {"_id":9,"title" : "Pondicherry Mahabalipuram","route":"Day 1:Chennai–Kanchipuram (1 Night)-->Day 2:Kanchipuram–Mahabalipuram–Pondicherry (3 Nights)-->Day 3:Pondicherry-->Day 4:Pondicherry–Chidambaram–Pichavaram–Pondicherry-->Day 5:Pondicherry–Chennai–Departure","price":"₹49,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/senior5.jpg", "rb").read())},
             {"_id":10,"title" : "Varanasi Ayodhya Lucknow","route":"Day 1:Lucknow (2 Nights)-->Day 2:Lucknow-->Day 3:Lucknow–Ayodhya (1 Night)-->Day 4:Ayodhya–Prayagraj (1 Night)-->Day 5:Prayagraj–Varanasi (3 Nights)-->Day 6:Varanasi-->Day 7:Varanasi–Sarnath–Varanasi-->Day 8:Varanasi–Departure","price":"₹49,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/senior6.jpg", "rb").read())},
             {"_id":11,"title" : "Port Blair Escape","route":"Day 1:Arrive Andaman-Cellular Jail and Light n Sound Show at Cellular Jail-->Port Blair–Havelock–Port Blair-->Day 3:Port Blair–Day Trip to Coral Island (North Bay) and Ross Island-->Day 4:Port Blair-Hometown","price":"₹20,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/fam4.jpg", "rb").read())},
             {"_id":12,"title" : "Goa with Pride Sun Village Resort","route":"Day 1:Goa Airport-Hotel (3 Nights)-->Day 2:Goa–Goa sightseeing-->Day 3:Goa–Day is at leisure-->Day 4:Goa–Departure to hometown","price":"₹16,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/fam3.jpg", "rb").read())},
             {"_id":13,"title" : "Statue of Unity with Narmada tent city","route":"Day 1:Vadodara–Narmada Tent City (2 Nights)-->Day 2 :Narmada Tent City-->Day 3:Narmada Tent City-Vadodara","price":"₹38,000","accomodation":"Processing the best for you!We are in the process of booking the accommodation for this tour. We will update it here, as we are done.Post Booking, you will be notified through your contact details about all tour related updates.","image" : Binary(open("D:/TravistorMain/static/images/fam6.jpg", "rb").read())}]


result = collection.insert_many(data_to_add)